const SUCCESS_CODE = 0; // 请求成功
// const LOGIN_ERROR = 5000; // 登录失败
// const FILE_ERROR = 6000; // 文件上传异常
// const ACTIVITI_ERROR = 7000; // 流程异常
// const COPY_PROPERTIES_ERROR = 7100; // 复制属性错误
// const PARAMETER_ERROR = 8001; // 参数校验异常
// const PERMISSION_DENIED = 9001; // 权限拒绝
// const UNKNOWN_ABNORMAL = 9002; // 未知异常
// const INVALID_USER = 9003; // 账户不存在，该用户可能未注册或已失效
// const ACCOUNT_KEY_EMPTY = 9004; // 用户名为空
// const ACCOUNT_ALREADY_EXIST = 9005; // 用户名已存在
// const ERROR_PASSWORD = 9006; // 密码错误
const TOKEN_FORMAT_ERROR = 9009; // token格式错误，不是有效token
const TOKEN_INVALID = 9010; // token过期
const TOKEN_CRYPT_ERROR = 9011; // token加解密异常
// const JSON_TRANSFER_ERROR = 9200; // JSON转化异常
// const CLIENT_NOT_REGISTER = 9300; // 业务系统未注册
// const CLIENT_ALREADY_REGISTER = 9301; // 业务系统已注册
// const CLIENT_ROLE_NOT_EXIST = 9400; // 该业务系统该角色不存在
// const SYSTEM_ERROR = 9999; // 系统异常，请稍后重试
const PEOJECT_CONTENT_ERROR = 7200; // 项目管理-内容不存在
const PEOJECT_ACCESS_ERROR = 9040; // 用户没有该项目的权限
